version: '3'

# Will be interesting to try adding the data to es for search later
services:
  es:
    container_name: elasticsearch
    image: elasticsearch:7.16.3
    ports:
      - "9200:9200"
    environment:
      - cluster.name=weatherca
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
